# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: ktlint detekt check
        run: ./gradlew ktlintCheck detekt

      - name: Upload ktlint report
        uses: actions/upload-artifact@v2
        with:
          name: ktlint
          path: ./**/build/reports/ktlint/
      - name: Upload detekt report
        uses: actions/upload-artifact@v2
        with:
          name: detekt
          path: ./**/build/reports/detekt/

      - name: Test with Gradle
        run: ./gradlew test

      - name: Upload tests report
        uses: actions/upload-artifact@v2
        with:
          name: tests-report
          path: ./**/build/reports/tests/
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./**/build/test-results/
